# Generated by Django 3.1.2 on 2020-12-02 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cd_cliente', models.UUIDField(db_column='cd_cliente', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('-', 'Prefiro não dizer')], max_length=1, verbose_name='Sexo')),
            ],
        ),
    ]
